apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- observer-samenode.yaml
- observer-othernode.yaml

configMapGenerator:
- name: observer-script
  options:
    labels:
      app.kubernetes.io/part-of: netpol-observer
  files:
  - run-observer.sh